Repository PelionIoT/distro-pelion-edge, pull requests merged in 2021-03, with the labels that each got.

#124 Sync global-node-modules with snap-pelion-edge build
  global-node-modules/deb/build.sh
Labels: do not merge

#132 mbed-edge-core: add platform version file
  mbed-edge-core-devmode/deb/build.sh
  mbed-edge-core-devmode/deb/debian/files/mbed_cloud_client_user_config.h
  mbed-edge-core-devmode/deb/debian/patches/Read-platform-version-files-into-LWM2M-resources.patch
  mbed-edge-core-devmode/deb/debian/patches/series
  mbed-edge-core/deb/build.sh
  mbed-edge-core/deb/debian/files/mbed_cloud_client_user_config.h
  mbed-edge-core/deb/debian/patches/Read-platform-version-files-into-LWM2M-resources.patch
  mbed-edge-core/deb/debian/patches/series
Labels: Ready

#133 Port over mbed-edge-core-devmode patches to mbed-edge-core
  mbed-edge-core/deb/build.sh
  mbed-edge-core/deb/debian/files/arm_update_activate.sh
  mbed-edge-core/deb/debian/files/arm_update_active_details.sh
  mbed-edge-core/deb/debian/files/arm_update_installer.sh
  mbed-edge-core/deb/debian/files/osreboot.c
  mbed-edge-core/deb/debian/install
  mbed-edge-core/deb/debian/patches/Broadcast-gateway-stats-to-LWM2M-resources.patch
  mbed-edge-core/deb/debian/patches/Fix-CPU-Temp-Path.patch
  mbed-edge-core/deb/debian/patches/Fixed-edge-cloud-write-errors.patch
  mbed-edge-core/deb/debian/patches/Remove-Version.patch
  mbed-edge-core/deb/debian/patches/allow-resources-to-be-named.patch
  mbed-edge-core/deb/debian/patches/fix-bug-dynamic-resources-should-be-updatable-by-the.patch
  mbed-edge-core/deb/debian/patches/fix-calculation-of-remaining-buffer-size-when-callin.patch
  mbed-edge-core/deb/debian/patches/force-port-443.patch
  mbed-edge-core/deb/debian/patches/patch-mbed-edge-with-the-ability-to-override-pelion-.patch
  mbed-edge-core/deb/debian/patches/series
Labels: Do Not Merge
